r

diff --git a/.github/workflows/BOpenWrt-ipv6-all.yml b/.github/workflows/BOpenWrt-ipv6-all.yml
--- a/.github/workflows/BOpenWrt-ipv6-all.yml
+++ b/.github/workflows/BOpenWrt-ipv6-all.yml
@@ -38,7 +38,8 @@ jobs:
     name: Build OpenWrt firmware
 
 
-    runs-on: ubuntu-20.04
+
+    runs-on: ubuntu-latest
 
     if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
 
@@ -73,27 +74,23 @@ jobs:
          else
              echo "CPU NO！！！"
              echo "CKCPU=failure" >> $GITHUB_ENV
-             exit 1
+             # exit 1
+             npm run lint
+             #- travis_retry npm test
+             npm AOpenWrt-ipv6-mini
          fi
       - name: Space cleanup
         env:
           DEBIAN_FRONTEND: noninteractive
         run: |
-          # sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
-          # sudo -E apt-get -qq update
-          # sudo -E apt-get -qq install $(curl -fsSL https://github.com/loso3000/mypk/raw/master/build/depends-ubuntu-2004)
           docker rmi `docker images -q`
-          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc /swapfile
-          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
-          sudo -E apt-mark hold grub-efi-amd64-signed
-          sudo -E apt update
-          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
-          sudo -E apt -y full-upgrade
-          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
-          sudo -E systemctl daemon-reload
-          sudo -E apt -y autoremove --purge
-          sudo -E apt clean
-          sudo -E timedatectl set-timezone "Asia/Shanghai"
+          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
+          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
+          sudo -E apt-get update
+          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
+          sudo -E apt-get -y autoremove --purge
+          sudo -E apt-get clean
+          sudo timedatectl set-timezone "Asia/Shanghai"
           sudo mkdir -p /workdir
           sudo chown $USER:$GROUPS /workdir
       - name: git lede
@@ -103,15 +100,17 @@ jobs:
           git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
           ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
           ls
-          df -h
       - name: Update feeds
         run: | 
           cd openwrt
           ./scripts/feeds update -a
-      - name: Install Feeds
-        run: |
-          cd openwrt
           ./scripts/feeds install -a
+      #- name: Cache
+      #  uses: klever1988/cachewrtbuild@main
+      #  with:
+      #    ccache: 'true'
+      #    prefix: 'openwrt'
+      #    mixkey: 'x86'
       - name: Update package
         run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ./openwrt/.config
@@ -120,43 +119,50 @@ jobs:
           echo "FIRMWARE=$PWD" >> $GITHUB_ENV
           echo "DATA=`date +%Y%m%d_%H -d +"12"hour`" >> $GITHUB_ENV
           echo "${{ env.FIRMWARE }} =----= ${{ env.DATA }}"
+         
          cd openwrt
          $GITHUB_WORKSPACE/$DIY_P1_SH
          $GITHUB_WORKSPACE/$DIY_P2_SH amd64
          chmod -R 755 .
-          df -h
-
       - name: Generate configuration file
+
         run: |
          cd openwrt
           make defconfig
+      #- name: Set ccache
+       # uses: klever1988/cachewrtbuild@main
+       # with:
+       #  ccache: 'true'
+       #  prefix: ${{ github.workspace }}/openwrt
       - name: Make download
         working-directory: ./openwrt
         run: |
-          make download -j50
-          find dl -size -1024c -exec ls -l {} \;
+          make download -j8
           find dl -size -1024c -exec rm -f {} \;
-          df -h
-      - name: Generate init
+          
+               
+      - name: Compile Packages
+        id: compile
+        run: |
+         df -h
+         cd openwrt
+         echo -e "$(nproc) thread compile"
+         make tools/compile -j$(nproc) || make tools/compile -j72
+         make toolchain/compile -j$(nproc) || make toolchain/compile -j72
+         make target/compile -j$(nproc) || make target/compile -j72 IGNORE_ERRORS=1
+         make diffconfig
+         make package/compile -j$(nproc) IGNORE_ERRORS=1 || make package/compile -j72 IGNORE_ERRORS=1
+         make package/index
+      - name: Generate Firmware
         run: |
          df -h
          cd openwrt 
-         # $GITHUB_WORKSPACE/$DIY_P2_SH amd64
          mkdir -p files/etc/uci-defaults/
-         cp $GITHUB_WORKSPACE/scriptx/init-settingsw.sh files/etc/uci-defaults/99-init-settings
-         df -h
-      - name: Compile firmware
-        run: |
-          cd openwrt 
-          make -j$(nproc) || make -j1 V=s
-          echo "======================="
-          echo "Space usage:"
-          echo "======================="
-          df -h
-          echo "======================="
-          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
-          du -h --max-depth=1 ./build_dir
-          du -h --max-depth=1 ./bin
+         cp $GITHUB_WORKSPACE/scriptx/init-settings.sh files/etc/uci-defaults/99-init-settings
+         make package/install -j$(nproc) || make package/install -j1 V=s
+         make target/install -j$(nproc) || make target/install -j1 V=s
+         make checksum
+          echo $?
 
       - name: Prepare Artifact
         run: |
