aa

diff --git a/.github/workflows/BOpenWrt-Plus.yml b/.github/workflows/BOpenWrt-Plus.yml
--- a/.github/workflows/BOpenWrt-Plus.yml
+++ b/.github/workflows/BOpenWrt-Plus.yml
@@ -32,6 +32,7 @@ jobs:
 
     if: github.event.repository.owner.id == github.event.sender.id
 
+ 
     steps:
 
       - name: Checkout
@@ -39,6 +40,7 @@ jobs:
         with:
           ref: master
       - name: Check server performance
+        id: checkcpu
         run: |
          echo "警告⚠"
          echo "若分配的服务器性能不足，务必及时取消，重新运行！"
@@ -47,6 +49,7 @@ jobs:
          echo -e "-------------- ------------CPU信息------------------------------------------\n"
          echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
          echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
+         
          echo "-------------------------------内存信息-------------------------------------------"
          echo "已安装内存详细信息："
          sudo lshw -short -C memory | grep GiB
@@ -54,8 +57,15 @@ jobs:
          echo "-----------------------------硬盘信息---------------------------------------------"
          echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
          echo "硬盘详情："
-         
-         df -Th
+         df -Th 
+         if grep  "8272" "/proc/cpuinfo" || grep  "8370" "/proc/cpuinfo" ; then
+          echo "CPU YES！！！"
+          echo "CKCPU=success" >> $GITHUB_ENV
+         else
+             echo "CPU NO！！！"
+             echo "CKCPU=failure" >> $GITHUB_ENV
+             exit 1
+         fi
       - name: Space cleanup
         env:
           DEBIAN_FRONTEND: noninteractive
