dz

diff --git a/.github/workflows/OpenWrt-mini-dz.yml b/.github/workflows/OpenWrt-mini-dz.yml
--- a/.github/workflows/OpenWrt-mini-dz.yml
+++ b/.github/workflows/OpenWrt-mini-dz.yml
@@ -20,21 +20,26 @@ env:
   DIY_P1_SH: dz.sh
   DIY_P2_SH: script/clash-core.sh
 
+permissions:
+  contents: read
+
 jobs:
 
   build_openwrt:
 
-    name: OpenWrt_Build 
+    permissions:
+      contents: write # for release creation
+
+    name: Build OpenWrt firmware
 
     runs-on: ubuntu-latest
 
-    if: github.event.repository.owner.id == github.event.sender.id
+    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
 
     steps:
 
-
       - name: Checkout
-        uses: actions/checkout@main
+        uses: actions/checkout@v2
         with:
           ref: master
       - name: Check server performance
@@ -42,7 +47,7 @@ jobs:
          echo "警告⚠"
          echo "若分配的服务器性能不足，务必及时取消，重新运行！"
          echo "已知编译成功CPU型号：8370C,8171M"
-         echo "已知性能不足CPU型号：8272CL"
+         echo "已知性能不足CPU型号：8272CL E5-2673"
          echo -e "-------------- ------------CPU信息------------------------------------------\n"
          echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
          echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
@@ -54,6 +59,15 @@ jobs:
          echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
          echo "硬盘详情："
          df -Th
+         
+         if grep  "8272" "/proc/cpuinfo" || grep  "8370" "/proc/cpuinfo" ; then
+          echo "CPU YES！！！"
+          echo "CKCPU=success" >> $GITHUB_ENV
+         else
+             echo "CPU NO！！！"
+             echo "CKCPU=failure" >> $GITHUB_ENV
+             exit 1
+         fi
       - name: Space cleanup
         env:
           DEBIAN_FRONTEND: noninteractive
@@ -65,50 +79,52 @@ jobs:
           sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean
-          df -h
           sudo timedatectl set-timezone "Asia/Shanghai"
-      - name: Clone Source Code
+          sudo mkdir -p /workdir
+          sudo chown $USER:$GROUPS /workdir
+      - name: git lede
+        working-directory: /workdir
         run: |
-         df -hT $PWD
+          df -hT $PWD
           git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
-      - name: Cache
-        uses: klever1988/cachewrtbuild@main
-        with:
-          ccache: 'true'
-          prefix: ${{ github.workspace }}/openwrt
-          clean: 'true'
+          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
+          ls
       - name: Update feeds
-        run: |
+        run: | 
           cd openwrt
-          git clone https://github.com/sirpdboy/sirpdboy-package ./package/diy
-          echo "DATA=$(date +'%Y-%m-%d'-d +"12"hour) \n" >> $GITHUB_ENV
           ./scripts/feeds update -a
           ./scripts/feeds install -a
+      #- name: Cache
+      #  uses: klever1988/cachewrtbuild@main
+      #  with:
+      #    ccache: 'true'
+      #    prefix: 'openwrt'
+      #    mixkey: 'x86'
       - name: Update package
         run: |
-         [ -e $CONFIG_FILE ] && cat $CONFIG_FILE  >> ./openwrt/.config
+         [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ./openwrt/.config
          chmod +x ./$DIY_P1_SH
-         chmod +x ./$DIY_P2_SH 
+         chmod +x ./$DIY_P2_SH
+          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
+          echo "DATA=`date +%Y%m%d_%H -d +"12"hour`" >> $GITHUB_ENV
+          echo "${{ env.FIRMWARE }} =----= ${{ env.DATA }}"
+         
          cd openwrt
-         ../$DIY_P1_SH
-         ../$DIY_P2_SH amd64
+         $GITHUB_WORKSPACE/$DIY_P1_SH
+         $GITHUB_WORKSPACE/$DIY_P2_SH amd64
          chmod -R 755 .
-      
       - name: Generate configuration file
-        working-directory: ./openwrt
         run: |
+          cd openwrt
           make defconfig
-      - name: Make download
-        working-directory: ./openwrt
-        run: |
           make download -j8
           find dl -size -1024c -exec rm -f {} \;
-             
       - name: Compile Packages
         id: compile
         run: |
          df -h
          cd openwrt
+         ls
          echo -e "$(nproc) thread compile"
          make tools/compile -j$(nproc) || make tools/compile -j72
          make toolchain/compile -j$(nproc) || make toolchain/compile -j72
@@ -116,19 +132,18 @@ jobs:
          make diffconfig
          make package/compile -j$(nproc) IGNORE_ERRORS=1 || make package/compile -j72 IGNORE_ERRORS=1
          make package/index
-         echo "::set-output name=COMPILE_STATUS::success"
-        
       - name: Generate Firmware
-        if: steps.compile.outputs.COMPILE_STATUS == 'success'
-        id: generate
         run: |
-         df -h
-         cd openwrt 
-         mkdir -p files/etc/uci-defaults/
-         cp ../scriptx/init-settings.sh files/etc/uci-defaults/99-init-settings
-         make package/install -j$(nproc) || make package/install -j1 V=s
-         make target/install -j$(nproc) || make target/install -j1 V=s
-         make checksum
+          cd openwrt
+          df -h
+          mkdir -p files/etc/uci-defaults/
+          cp $GITHUB_WORKSPACE/scriptx/init-settings.sh files/etc/uci-defaults/99-init-settings
+          #mkdir -p files/etc/opkg
+          #cp ../configs/opkg/distfeeds-packages-server.conf files/etc/opkg/distfeeds.conf.server
+         
+          make package/install -j$(nproc) || make package/install -j1 V=s
+          make target/install -j$(nproc) || make target/install -j1 V=s
+          make checksum
 
       - name: Prepare Artifact
         run: |
