x

diff --git a/.github/workflows/Openwrt-ac2100-im.yml b/.github/workflows/Openwrt-ac2100-im.yml
--- a/.github/workflows/Openwrt-ac2100-im.yml
+++ b/.github/workflows/Openwrt-ac2100-im.yml
@@ -20,16 +20,13 @@ env:
   FEEDS_CONF: feeds.conf.default
   CONFIG_FILE: xmra2100.im
   DIY_P1_SH: im.sh
+  CLASH_BINARY_PLATFORM: mipsle-softfloat
+  
 jobs:
-
   build_openwrt:
-
     name: OpenWrt_Build 
-
     runs-on: ubuntu-latest
-
     if: github.event.repository.owner.id == github.event.sender.id
-
     steps:
 
       - name: Checkout
@@ -53,6 +50,15 @@ jobs:
          echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
          echo "硬盘详情："
          df -Th
+         
+         if grep  "8272" "/proc/cpuinfo" || grep  "8370" "/proc/cpuinfo" ; then
+          echo "CPU YES！！！"
+          echo "CKCPU=success" >> $GITHUB_ENV
+         else
+             echo "CPU NO！！！"
+             echo "CKCPU=failure" >> $GITHUB_ENV
+             exit 1
+         fi
       - name: Space cleanup
         env:
           DEBIAN_FRONTEND: noninteractive
@@ -70,62 +76,74 @@ jobs:
              sudo timedatectl set-timezone "Asia/Shanghai"
              sudo mkdir -p /workdir
              sudo chown $USER:$GROUPS /workdir
-      - name: Get current date
-        id: date
-        run: |
-          echo "date=$(date +'%m/%d_%Y_%H/%M')" >> $GITHUB_ENV
-          echo "date2=$(date +'%m/%d %Y')" >> $GITHUB_ENV
-          echo "date3=$(date +'%m.%d')" >> $GITHUB_ENV
-          echo "date4=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
-      - name: Update feeds
+      - name: download
         run: |
           git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
           cd openwrt
-          git clone https://github.com/sirpdboy/sirpdboy-package ./package/diy
+          rm -rf ./tmp && rm -rf .config
+      - name: Update feeds
+        run: |
+          cd openwrt 
           ./scripts/feeds update -a
           ./scripts/feeds install -a
       - name: Update package
         run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ./openwrt/.config
+          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
+          echo "DATA=`TZ=UTC-8 date +%Y%m%d_%H -d +"12"hour`" >> $GITHUB_ENV
+          echo "${{ env.FIRMWARE }} =----= ${{ env.DATA }}"
          chmod +x ./$DIY_P1_SH
+         chmod +x ./script/clash-core.sh
          cd openwrt
          ../$DIY_P1_SH
+         # ../script/clash-core.sh $CLASH_BINARY_PLATFORM 
          chmod -R 755 .
       - name: Generate configuration file
-        working-directory: ./openwrt
         run: |
-          make defconfig
+          cd openwrt
+          make defconfig 
       - name: Make download
-        working-directory: ./openwrt
         run: |
+          cd openwrt
           make download -j8
-          find dl -size -1024c -exec rm -f {} \;
-      - name: Compile firmware
-        working-directory: ./openwrt
+      - name: Compile Packages
+        id: compile
         run: |
-          make -j$(nproc) || make -j1 V=s
-          echo "======================="
-          echo "Space usage:"
-          echo "======================="
-          df -h
-          echo "======================="
-          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
-          du -h --max-depth=1 ./build_dir
-          du -h --max-depth=1 ./bin
-      - name: Upload Firmware
-        uses: actions/upload-artifact@main
-        with:
-          name: OpenWrt-IPV6-xmra2100-Firmware
-          path: ./openwrt/bin/targets/
-      - name: Upload  IPK
-        uses: actions/upload-artifact@main
-        with:
-          name: OpenWrt-IPV6-xmra2100-Ipk
-          path: ./openwrt/bin/packages
+         df -h
+         cd openwrt
+         echo -e "$(nproc) thread compile"
+         make tools/compile -j$(nproc) || make tools/compile -j72
+         make toolchain/compile -j$(nproc) || make toolchain/compile -j72
+         make target/compile -j$(nproc) || make target/compile -j72 IGNORE_ERRORS=1
+         make diffconfig
+         make package/compile -j$(nproc) IGNORE_ERRORS=1 || make package/compile -j72 IGNORE_ERRORS=1
+         make package/index
+         
+      - name: Generate Firmware
+        id: generate
+        run: |
+         df -h
+         cd openwrt 
+         # mkdir -p files/etc/uci-defaults/
+         # cp ../scriptx/init-settings.sh files/etc/uci-defaults/99-init-settings
+         make package/install -j$(nproc) || make package/install -j1 V=s
+         make target/install -j$(nproc) || make target/install -j1 V=s
+         make checksum
       - name: Prepare Artifact
         run: |
           mkdir ./ac2100
-          find ./openwrt/bin/targets/ -name "*sysupgrade*" | xargs -i mv -f {} ./ac2100/
+          find ./openwrt/bin/targets/ -name "*squashfs*" | xargs -i mv -f {} ./ac2100/
           cd ./ac2100
           # rename -v "s/friendlyarm_//" *
-          # gzip *.bin
+          gzip *.bin | true
+          # gzip *.img | true
+      - name: Upload Firmware
+        uses: actions/upload-artifact@main
+        with:
+          name: ${{ env.DATA }}-SirpdboyOpenWrt-IPV6-xmra2100-Firmware
+          path: ./ac2100
+      - name: Upload  bin
+        uses: actions/upload-artifact@main
+        with:
+          name: ${{ env.DATA }}-SirpdboyOpenWrt-IPV6-xmra2100-bin
+          path: ./openwrt/bin/
