dz

diff --git a/.github/workflows/Openwrt-r2s-lean-s.yml b/.github/workflows/Openwrt-r2s-lean-s.yml
--- a/.github/workflows/Openwrt-r2s-lean-s.yml
+++ b/.github/workflows/Openwrt-r2s-lean-s.yml
@@ -1,4 +1,4 @@
-name: Openwrt-r2s-lean-s
+name: Openwrt-r2s-lean-dz
 
 
 on:
@@ -9,27 +9,39 @@ on:
         description: 'SSH connection to Actions'
         required: false
         default: 'false'
- #   watch:
- #     types: started
+  watch:
+    types: started
 #  schedule:
 #    - cron: 0 21 */7 * * 
 
 env:
-  REPO_URL: https://github.com/coolsnowwolf/lede
-  REPO_BRANCH: master
+
+  REPO_URL: https://github.com/DHDAXCW/lede-rockchip
+  #  https://github.com/loso3000/immortalwrt-1.git
+  REPO_BRANCH: stable
+  #REPO_BRANCH: openwrt-18.06-k5.4
   FEEDS_CONF: feeds.conf.default
-  CONFIG_FILE: r2s.lienol
   DIY_P1_SH: dz.sh
-  DIY_P2_SH: update_package_all.sh
+  DIY_P2_SH: script/clash-core.sh
+  CONFIG_FILE: r2s.lienol
+  TZ: Asia/Shanghai
+  
+
+permissions:
+  contents: read
+
 jobs:
 
   build_openwrt:
 
-    name: OpenWrt_Build 
+    permissions:
+      contents: write # for release creation
+
+    name: Build OpenWrt firmware
 
     runs-on: ubuntu-latest
 
-    if: github.event.repository.owner.id == github.event.sender.id
+    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
 
     steps:
 
@@ -37,81 +49,160 @@ jobs:
         uses: actions/checkout@v2
         with:
           ref: master
+          
+      - name: Check server performance
+        run: |
+         echo "警告⚠"
+         echo "若分配的服务器性能不足，务必及时取消，重新运行！"
+         echo "已知编译成功CPU型号：8370C,8171M"
+         echo "已知性能不足CPU型号：8272CL E5-2673"
+         echo -e "-------------- ------------CPU信息------------------------------------------\n"
+         echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
+         echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
+         echo "-------------------------------内存信息-------------------------------------------"
+         echo "已安装内存详细信息："
+         sudo lshw -short -C memory | grep GiB
+         echo -e "\n"
+         echo "-----------------------------硬盘信息---------------------------------------------"
+         echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
+         echo "硬盘详情："
+         df -Th
+         
+         if grep  "8272" "/proc/cpuinfo" || grep  "8370" "/proc/cpuinfo" ; then
+          echo "CPU YES！！！"
+          echo "CKCPU=success" >> $GITHUB_ENV
+         else
+             echo "CPU NO！！！"
+             echo "CKCPU=failure" >> $GITHUB_ENV
+             npm AOpenwrt-r2s-lean
+             #exit 1
+         fi
       - name: Space cleanup
         env:
           DEBIAN_FRONTEND: noninteractive
         run: |
-          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
-          sudo -E apt-get -qq update
-          sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
-          sudo -E apt-get -qq autoremove --purge
-          sudo -E apt-get -qq clean
-          sudo timedatectl set-timezone "Asia/Shanghai"
-      - name: Get current date
-        id: date
+          docker rmi `docker images -q`
+          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /usr/lib/jvm /opt/ghc /swapfile
+          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
+          sudo -E apt-mark hold grub-efi-amd64-signed
+          sudo -E apt update
+          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
+          sudo -E apt -y full-upgrade
+          sudo -E apt -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
+          sudo -E systemctl daemon-reload
+          sudo -E apt -y autoremove --purge
+          sudo -E apt clean
+          sudo -E timedatectl set-timezone "Asia/Shanghai"
+          sudo mkdir -p /workdir
+          sudo chown $USER:$GROUPS /workdir
+      - name: git lede
+        working-directory: /workdir
         run: |
-          echo "date=$(date +'%m/%d_%Y')" >> $GITHUB_ENV
-      - name: Update feeds
-        run: |
+          df -hT $PWD
           git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
+          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
+          ls
+          df -h
+      - name: Update feeds
+        run: | 
           cd openwrt
-          #sed -i 's/#src-git helloworld/src-git helloworld/g' ./feeds.conf.default
-          #sed -i 's/coolsnowwolf/sirpdboy/g' ./feeds.conf.default
-          git clone https://github.com/sirpdboy/sirpdboy-package ./package/diy
           ./scripts/feeds update -a
           ./scripts/feeds install -a
       - name: Update package
         run: |
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE ./openwrt/.config
          chmod +x ./$DIY_P1_SH
+         chmod +x ./$DIY_P2_SH
+          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
+          echo "DATA=`date +%Y%m%d_%H -d +"12"hour`" >> $GITHUB_ENV
+          echo "${{ env.FIRMWARE }} =----= ${{ env.DATA }}"
          cd openwrt
-         ../$DIY_P1_SH
+         $GITHUB_WORKSPACE/$DIY_P1_SH
          chmod -R 755 .
-      - name: Generate configuration file
-        working-directory: ./openwrt
-        run: |
           make defconfig
-      - name: Make download
-        working-directory: ./openwrt
-        run: |
-          make download -j8
-          find dl -size -1024c -exec rm -f {} \;
-      - name: Compile firmware
-        working-directory: ./openwrt
-        run: |
-          make -j$(nproc) || make -j1 V=s
-          echo "======================="
-          echo "Space usage:"
-          echo "======================="
           df -h
-          echo "======================="
-          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
-          du -h --max-depth=1 ./build_dir
-          du -h --max-depth=1 ./bin
+      - name: Generate configuration file
+        run: |
+          cd openwrt
+          make download -j32
+          find dl -size -1024c -exec ls -l {} \;
+          find dl -size -1024c -exec rm -f {} \;
+          df -h
+               
+      - name: Compile Packages
+        id: compile
+        run: |
+         df -h
+         cd openwrt
+         echo -e "$(nproc) thread compile"
+         make tools/compile -j$(nproc) || make tools/compile -j72
+         make toolchain/compile -j$(nproc) || make toolchain/compile -j72
+         make target/compile -j$(nproc) || make target/compile -j72 IGNORE_ERRORS=1
+         make diffconfig
+         make package/compile -j$(nproc) IGNORE_ERRORS=1 || make package/compile -j72 IGNORE_ERRORS=1
+         make package/index
+      - name: Generate Firmware
+        run: |
+         df -h
+         cd openwrt 
+         mkdir -p files/etc/uci-defaults/
+         $GITHUB_WORKSPACE/$DIY_P2_SH arm64
+         cp $GITHUB_WORKSPACE/scriptx/init-settings.sh files/etc/uci-defaults/99-init-settings
+         make package/install -j$(nproc) || make package/install -j1 V=s
+         make target/install -j$(nproc) || make target/install -j1 V=s
+         make checksum
+          
+      - name: Upload ipk Firmware
+        uses: actions/upload-artifact@main
+        with:
+          name: ${{ env.DATA }}-RxsOpenWrt-Ipv6-Vip-ipk-Firmware
+          path: ./openwrt/bin/
+          
+      - name: Prepare Artifact
+        run: |
+          mkdir -p ./firmwarer2s
+          mkdir -p ./firmwarer4s
+          mkdir -p ./firmwarer4se
+          ls
+          find ./openwrt/bin/targets/ -name "*r2s-ext4-sysupgrade.img*" | xargs -i mv -f {} ./firmwarer2s
+          find ./openwrt/bin/targets/ -name "*r2s-squashfs-sysupgrade.img*" | xargs -i mv -f {} ./firmwarer2s
+          cd ./firmwarer2s  
+          #gzip *.img | true
+          echo -e "Sirpdboy-R2S-Vip-${{ env.DATA }}\n" > 版本日期和MD5信息.txt
+          echo -e "【固件插件说明与各版本下载链接】：https://github.com/sirpdboy/openwrt/ \n"  >> 版本日期和MD5信息.txt
+          echo -e "MD5: \n" >> 版本日期和MD5信息.txt
+          md5sum *img* >> 版本日期和MD5信息.txt
+          find ${{ env.FIRMWARE }}/openwrt/bin/targets/ -name "*r4se-ext4-sysupgrade.img*" | xargs -i mv -f {} ${{ env.FIRMWARE }}/firmwarer4se
+          find ${{ env.FIRMWARE }}/openwrt/bin/targets/ -name "*r4se-squashfs-sysupgrade.img*" | xargs -i mv -f {} ${{ env.FIRMWARE }}/firmwarer4se
+          cd ${{ env.FIRMWARE }}/firmwarer4se
+          #gzip *.img | true
+          echo -e "Sirpdboy-r4se-Vip-${{ env.DATA }}\n" > 版本日期和MD5信息.txt
+          echo -e "【固件插件说明与各版本下载链接】：https://github.com/sirpdboy/openwrt/ \n"  >> 版本日期和MD5信息.txt
+          echo -e "MD5: \n" >> 版本日期和MD5信息.txt
+          md5sum *img* >> 版本日期和MD5信息.txt
+          find ${{ env.FIRMWARE }}/openwrt/bin/targets/ -name "*r4s-ext4-sysupgrade.img*" | xargs -i mv -f {} ${{ env.FIRMWARE }}/firmwarer4s
+          find ${{ env.FIRMWARE }}/openwrt/bin/targets/ -name "*r4s-squashfs-sysupgrade.img*" | xargs -i mv -f {} ${{ env.FIRMWARE }}/firmwarer4s
+          cd ${{ env.FIRMWARE }}/firmwarer4s
+          #gzip *.img | true
+          echo -e "Sirpdboy-R4S-Vip-${{ env.DATA }}\n" > 版本日期和MD5信息.txt
+          echo -e "【固件插件说明与各版本下载链接】：https://github.com/sirpdboy/openwrt/ \n"  >> 版本日期和MD5信息.txt
+          echo -e "MD5: \n" >> 版本日期和MD5信息.txt
+          md5sum *img* >> 版本日期和MD5信息.txt
       - name: Upload Firmware
         uses: actions/upload-artifact@main
         with:
-          name: R2s-OpenWrt-IPV6-Firmware
-          path: ./openwrt/bin/targets/
-      - name: Upload  IPK
+          name: ${{ env.DATA }}-R2sOpenWrt-Ipv6-Vip-Firmwaredz
+          path: ./firmwarer2s
+      - name: Upload Firmware
         uses: actions/upload-artifact@main
         with:
-          name: R2s-OpenWrt-IPV6-Ipk
-          path: ./openwrt/bin/packages
-      - name: Prepare Artifact
-        run: |
-          mkdir ./r2s
-          find ./openwrt/bin/targets/ -name "*combined*" -or -name "*sysupgrade*" | xargs -i mv -f {} ./r2s/
-          gzip *.*
+          name: ${{ env.DATA }}-R4seOpenWrt-Ipv6-Vip-Firmwaredz
+          path: ./firmwarer4se
 
-      - name: Upload Firmware wetransfer
-        run: |
-          curl -fsSL git.io/file-transfer | sh
-          ./transfer wet -s -p 16 --no-progress ./r2s/ 2>&1 | tee wetransfer.log
-          echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
-
-      - name: Delete workflow runs
-        uses: GitRML/delete-workflow-runs@main
+      - name: Upload Firmware
+        uses: actions/upload-artifact@main
         with:
+          name: ${{ env.DATA }}-R4sOpenWrt-Ipv6-Vip-Firmwaredz
+          path: ./firmwarer4s
           retain_days: 14
           keep_minimum_runs: 3
