ff

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -45,8 +45,12 @@ jobs:
          echo -e "-------------- ------------CPU信息------------------------------------------\n"
          echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
          echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
-         if ! grep -q "8370|8272" "/proc/cpuinfo" ; then
-         echo "CPU ERROR！！！ EXIT!!"
+         if grep -q "8370|8272" "/proc/cpuinfo" ; then
+         echo "CPU ERROR！！！ EXIT 111111"
+         exit
+         fi
+         if ! grep -Eq "8370|8272" "/proc/cpuinfo" ; then
+         echo "CPU ERROR ！！！ EXIT 22222"
          exit
          fi
          
